HARMONY-1985: Re-add work-failer to local deployment script since it was removed accidentally

diff --git a/bin/deploy-services b/bin/deploy-services
--- a/bin/deploy-services
+++ b/bin/deploy-services
@@ -52,6 +52,15 @@ if [ ! "$LOCAL_DEV" = true ]; then
   # create the cron service
   file="services/cron-service/config/service-template.yaml"
   if [ ! -f "$file" ]; then
+    echo "cron service template was not found."
+    exit 1
+  fi
+  envsubst < $file | kubectl apply -f - -n harmony
+fi
+
+# create the work failer
+  file="services/work-failer/config/service-template.yaml"
+  if [ ! -f "$file" ]; then
     echo "work failer template was not found."
     exit 1
   fi
