HARMONY-1573: Try macos-13 and test with less services.

diff --git a/bin/deploy-services b/bin/deploy-services
--- a/bin/deploy-services
+++ b/bin/deploy-services
@@ -36,12 +36,12 @@ if [ ! "$LOCAL_DEV" = true ]; then
   fi
 
   # create the work updaters
-  file="services/work-updater/config/service-template-large.yaml"
-  if [ ! -f "$file" ]; then
-    echo "large work updater template was not found."
-    exit 1
-  fi
-  envsubst < $file | kubectl apply -f - -n harmony
+  # file="services/work-updater/config/service-template-large.yaml"
+  # if [ ! -f "$file" ]; then
+  #   echo "large work updater template was not found."
+  #   exit 1
+  # fi
+  # envsubst < $file | kubectl apply -f - -n harmony
   file="services/work-updater/config/service-template-small.yaml"
   if [ ! -f "$file" ]; then
     echo "small work updater template was not found."
@@ -49,21 +49,21 @@ if [ ! "$LOCAL_DEV" = true ]; then
   fi
   envsubst < $file | kubectl apply -f - -n harmony
 
-  # create the work reaper
-  file="services/work-reaper/config/service-template.yaml"
-  if [ ! -f "$file" ]; then
-    echo "work reaper template was not found."
-    exit 1
-  fi
-  envsubst < $file | kubectl apply -f - -n harmony
+#   # create the work reaper
+#   file="services/work-reaper/config/service-template.yaml"
+#   if [ ! -f "$file" ]; then
+#     echo "work reaper template was not found."
+#     exit 1
+#   fi
+#   envsubst < $file | kubectl apply -f - -n harmony
 
-  # create the work failer
-  file="services/work-failer/config/service-template.yaml"
-  if [ ! -f "$file" ]; then
-    echo "work failer template was not found."
-    exit 1
-  fi
-  envsubst < $file | kubectl apply -f - -n harmony
+#   # create the work failer
+#   file="services/work-failer/config/service-template.yaml"
+#   if [ ! -f "$file" ]; then
+#     echo "work failer template was not found."
+#     exit 1
+#   fi
+#   envsubst < $file | kubectl apply -f - -n harmony
 fi
 
 if [ "$current_context" != "colima" ]; then
