HARMONY-1323: Add context guard to deploy script

diff --git a/bin/deploy-services b/bin/deploy-services
--- a/bin/deploy-services
+++ b/bin/deploy-services
@@ -8,6 +8,15 @@ source ".env"
 set +a
 eval "$env_save"
 
+if [ "$NODE_ENV" == "development" ]; then
+  current_context=$(kubectl config current-context)
+  if [ "$current_context" != "docker-desktop" ] && [ "$current_context" != "minikube" ]; then
+    echo 'ERROR: Attempting to use a non-local k8s context while deploying to a development environment.'
+    echo "$current_context"
+    exit 1
+  fi
+fi
+
 . ./bin/create-k8s-config-maps-and-secrets
 
 # create the query-cmr service
