HARMONY-1538: Add npm script to push all images to ECR

diff --git a/services/giovanni-adapter/bin/push-image b/services/giovanni-adapter/bin/push-image
--- a/services/giovanni-adapter/bin/push-image
+++ b/services/giovanni-adapter/bin/push-image
@@ -11,10 +11,22 @@ account=$(aws sts get-caller-identity --output text --query 'Account')
 # Need to remove \r returned on all aws commands run from Bamboo
 account=${account//$'\r'/}
 
+# let this block fail without exiting, so that we can retry with another command if necessary
+set +e
 login_command=$(aws ecr get-login --no-include-email --region ${region})
+login_status=$?
 # Need to remove \r returned on all aws commands run from Bamboo
 login_command=${login_command//$'\r'/}
 $login_command
+set -e
+
+# the previous login failed, so try using the updated command
+if [ $login_status -ne 0 ]; then
+  echo "Trying newer login command."
+  login_password=$(aws ecr get-login-password --region ${region})
+  login_password=${login_password//$'\r'/}
+  docker login --username AWS --password $login_password ${account}.dkr.ecr.${region}.amazonaws.com
+fi
 
 docker tag ${image}:${tag} ${account}.dkr.ecr.${region}.amazonaws.com/${image}:${tag}
 
