HARMONY-1573: Added docer pull to improve image build time.

diff --git a/.github/workflows/harmony-in-a-box.yml b/.github/workflows/harmony-in-a-box.yml
--- a/.github/workflows/harmony-in-a-box.yml
+++ b/.github/workflows/harmony-in-a-box.yml
@@ -25,28 +25,31 @@ jobs:
         brew install kubectl
         colima start --cpu 3 --memory 12 --with-kubernetes
 
+    - name: Pull down basic harmony docker images
+      run: bin/pull-harmony-images
+
     - name: Install dependencies
       run: npm ci
 
-    - name: Build harmony
+    - name: Build harmony image
       run: npm run build
 
     - name: Build all other images
       run: npm run build-all
 
-    - name: list images
-      run: docker images
-
     - name: Start harmony in a box
       run: KUBE_CONTEXT=colima bin/bootstrap-harmony
 
-    - name: Wait for the server to start
-      run: kubectl -n harmony get pods
-
-    - name: Run curl against harmony
+    - name: Check if harmony server is up
       id: curl
       run: |
-        HTTP_STATUS=$(curl -I -s -o /dev/null -w "%{http_code}" http://localhost:3000)
+        HTTP_STATUS=$(curl -I -s -o /dev/null -w "%{http_code}" "http://localhost:3000")
+        echo "harmony server status code: $HTTP_STATUS"
+
+    - name: Run harmony request
+      id: curl
+      run: |
+        HTTP_STATUS=$(curl -Ln -bj -w "%{http_code}" "http://localhost:3000/C1233800302-EEDTEST/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?granuleId=G1233800343-EEDTEST&format=image/tiff" -o ./output.tif)
         echo "::set-output name=http_status::$HTTP_STATUS"
 
     - name: Check HTTP status code
@@ -55,5 +58,20 @@ jobs:
           echo "HTTP request was successful!"
         else
           echo "HTTP request failed with status code ${{ steps.curl.outputs.http_status }}"
+          exit 1
+        fi
+
+    - name: Run a bad harmony request
+      id: curlx
+      run: |
+        HTTP_STATUS=$(curl -Ln -bj -w "%{http_code}" "http://localhost:3000/ogc-api-coverages/1.0.0/collections/all/coverage/rangeset?granuleId=G1233800343-EEDTEST&format=image/tiff" -o ./output.tif)
+        echo "::set-output name=http_status::$HTTP_STATUS"
+
+    - name: Check bad HTTP status code
+      run: |
+        if [[ "${{ steps.curlx.outputs.http_status }}" -eq 200 ]]; then
+          echo "HTTP request was successful!"
+        else
+          echo "HTTP request failed with status code ${{ steps.curlx.outputs.http_status }}"
           exit 1
         fi
